### ISSUE TITLE
Using Atom outside Composable function

### ISSUE THREAD

**Issue by du-nt** [soil-kt/soil#121]
**Please describe the feature you'd like to see including any solutions in mind if you have any**
How to use space like this
https://jotai.org/docs/guides/using-store-outside-react
```typescript
import { atom, useAtomValue, createStore, Provider } from 'jotai'

const timeAtom = atom(0)
const store = createStore()

store.set(timeAtom, (prev) => prev + 1) // Update atom's value
store.get(timeAtom) // Read atom's value

function Component() {
  const time = useAtomValue(timeAtom) // Inside React
  return (
    <div className="App">
      <h1>{time}</h1>
    </div>
  )
}

export default function App() {
  return (
    <Provider store={store}>
      <Component />
    </Provider>
  )
}
```

**Comment by ogaclejapan** [comment]
Thank you for your request ⭐ 

Unfortunately, due to lifecycle constraints on the Android platform, it is not recommended to store a store in a static area. This is because Android manages to save and restore on a per-Activity basis. Given this constraint, the Space library we provide is designed with a focus on state retention specifically within Compose. 

Check out the guide here: https://developer.android.com/topic/libraries/architecture/saving-states#onsaveinstancestate
